import { Product } from '../types';

export const CATALOG: Product[] = [
  {
    id: 'f1',
    title: 'Manteau en laine structure',
    brand: 'Maje',
    image: 'https://picsum.photos/seed/manteau1/400/600',
    affiliateUrl: 'https://elle.fr/shopping/manteau-maje',
    price: 345,
    currency: 'EUR',
    category: 'Woman > Coat',
    slot: 'outerwear',
    styleTags: ['chic', 'minimal'],
    colorHex: '#333333',
    weatherTags: ['froid', 'tempere'],
  },
  {
    id: 'f2',
    title: 'Pull cachemire col roule',
    brand: 'Sandro',
    image: 'https://picsum.photos/seed/pull1/400/600',
    affiliateUrl: 'https://elle.fr/shopping/pull-sandro',
    price: 185,
    currency: 'EUR',
    category: 'Woman > Knitwear',
    slot: 'top',
    styleTags: ['chic', 'casual'],
    colorHex: '#F5F5DC',
    weatherTags: ['froid', 'tempere'],
  },
  {
    id: 'f3',
    title: 'Pantalon large taille haute',
    brand: 'Claudie Pierlot',
    image: 'https://picsum.photos/seed/pantalon1/400/600',
    affiliateUrl: 'https://elle.fr/shopping/pantalon-cp',
    price: 165,
    currency: 'EUR',
    category: 'Woman > Trousers',
    slot: 'bottom',
    styleTags: ['chic', 'minimal'],
    colorHex: '#000000',
    weatherTags: ['froid', 'tempere', 'chaud'],
  },
  {
    id: 'f4',
    title: 'Bottines en cuir noir',
    brand: 'Jonak',
    image: 'https://picsum.photos/seed/shoes1/400/600',
    affiliateUrl: 'https://elle.fr/shopping/bottines-jonak',
    price: 145,
    currency: 'EUR',
    category: 'Woman > Shoes',
    slot: 'shoes',
    styleTags: ['chic', 'rock'],
    colorHex: '#000000',
    weatherTags: ['froid', 'tempere'],
  },
  {
    id: 'f5',
    title: "Robe d'ete a fleurs",
    brand: 'Ba&sh',
    image: 'https://picsum.photos/seed/robe1/400/600',
    affiliateUrl: 'https://elle.fr/shopping/robe-bash',
    price: 220,
    currency: 'EUR',
    category: 'Woman > Dress',
    slot: 'top',
    styleTags: ['boheme', 'casual'],
    colorHex: '#FFB6C1',
    weatherTags: ['chaud'],
  },
  {
    id: 'f6',
    title: 'Sandales en cuir dore',
    brand: 'K.Jacques',
    image: 'https://picsum.photos/seed/sandales1/400/600',
    affiliateUrl: 'https://elle.fr/shopping/sandales-kj',
    price: 195,
    currency: 'EUR',
    category: 'Woman > Shoes',
    slot: 'shoes',
    styleTags: ['boheme', 'casual'],
    colorHex: '#FFD700',
    weatherTags: ['chaud'],
  },
];
